# Generated by Django 6.0.5 on 2026-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trail_work_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_integration', models.CharField(choices=[('none', 'Disabled'), ('plugin', 'Option 1 — Facebook Page Plugin (show live feed on site)'), ('zapier', 'Option 3 — Zapier Webhook (auto-post announcements to Facebook)')], default='none', max_length=20)),
                ('facebook_page_url', models.URLField(blank=True, default='https://www.facebook.com/brainerdsnodeos')),
                ('zapier_webhook_url', models.URLField(blank=True, help_text='Paste your Zapier Catch Hook URL here')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
