# Generated by Django 6.0.5 on 2026-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_officer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('members', 'Members Only — shown on member dashboard'), ('public', 'Public — shown on home page & triggers Zapier'), ('both', 'Both — home page, member dashboard & Zapier')], default='members', max_length=10),
        ),
    ]
