# Generated by Django 6.0.5 on 2026-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_announcement_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
