# Generated by Django 6.0.5 on 2026-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_officer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, help_text='Facebook App ID (required for the Page Plugin to work)', max_length=50),
        ),
    ]
