# Generated by Django 6.0.5 on 2026-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_facebook_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brevo_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brevo_smtp_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Where officer alerts go (new applications, contact messages)', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resend_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_from_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_integration',
            field=models.CharField(choices=[('none', 'Disabled'), ('plugin', 'Page Plugin (embed feed on site — requires App ID)'), ('zapier', 'Zapier Auto-Post (auto-post announcements to Facebook)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='zapier_webhook_url',
            field=models.URLField(blank=True),
        ),
    ]
