# Generated by Django 6.0.5 on 2026-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_comms_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_accent_color',
            field=models.CharField(blank=True, default='#1363A2', help_text='Hex color for buttons and accents', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_footer_text',
            field=models.TextField(blank=True, default="You're receiving this because you're a member of the Brainerd Snodeos Snowmobile Club."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='Brainerd Snodeos', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_header_color',
            field=models.CharField(blank=True, default='#1363A2', help_text='Hex color for the email header bar', max_length=7),
        ),
    ]
