# Generated by Django 6.0.5 on 2026-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_email_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Short description shown in the selector', max_length=200)),
                ('from_name', models.CharField(default='Brainerd Snodeos', max_length=100)),
                ('header_color', models.CharField(default='#1363A2', max_length=7)),
                ('accent_color', models.CharField(default='#1363A2', max_length=7)),
                ('footer_text', models.TextField(blank=True, default="You're receiving this as a member of the Brainerd Snodeos Snowmobile Club.")),
                ('is_default', models.BooleanField(default=False, help_text='Default template used when none is specified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
