# Generated by Django 6.0.5 on 2026-05-19 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_email_template_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='template_announcement',
            field=models.ForeignKey(blank=True, help_text='Template for announcement email blasts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.emailtemplate'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='template_contact_reply',
            field=models.ForeignKey(blank=True, help_text='Template for auto-replies to contact form submitters', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.emailtemplate'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='template_member',
            field=models.ForeignKey(blank=True, help_text='Template for member-facing transactional emails (application approved, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.emailtemplate'),
        ),
    ]
