# Generated by Django 6.0.5 on 2026-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_template_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='header_image_url',
            field=models.URLField(blank=True, help_text='Publicly accessible image URL shown in the email header (replaces the ❄ snowflake)'),
        ),
    ]
