# Generated by Django 6.0.5 on 2026-05-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emailtemplate_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='header_image_url',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='email_headers/'),
        ),
    ]
