# Generated by Django 6.0.5 on 2026-05-19 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_emailtemplate_header_image_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('caution', 'Use Caution'), ('groomed', 'Recently Groomed')], default='open', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public — shown on trail conditions page'), ('members', 'Members Only — shown on member dashboard'), ('both', 'Both — trail conditions page & member dashboard')], default='both', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='template_trail_condition',
            field=models.ForeignKey(blank=True, help_text='Template for trail condition email blasts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.emailtemplate'),
        ),
    ]
