# Generated by Django 6.0.5 on 2026-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dues_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='dues_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
