# Generated by Django 6.0.5 on 2026-05-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dues_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('phone', 'Phone Number'), ('address', 'Street Address'), ('city', 'City'), ('state', 'State'), ('zip_code', 'Zip Code'), ('snowmobile_brand', 'Snowmobile Brand / Sled')], max_length=50, unique=True)),
                ('label', models.CharField(blank=True, help_text='Override the default label (leave blank to use default)', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Show this field on the registration form')),
                ('is_required', models.BooleanField(default=False, help_text='Make this field required')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
