# Generated by Django 6.0.5 on 2026-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='accepts_texts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='num_snowmobiles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='referral_source',
            field=models.TextField(blank=True),
        ),
    ]
