# Generated by Django 6.0.5 on 2026-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_site_admin',
            field=models.BooleanField(default=False, help_text='Full access including Communications and Settings'),
        ),
    ]
